import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Anouce from "@/components/anouncement";
import Header from "@/components/Header";
import Footer from "@/components/footer";
import { CartProvider } from "@/components/cartContext";
import {
  ClerkProvider,
  
} from '@clerk/nextjs'
import LoadingBar from "@/components/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const clerkPubKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

  return (
    <ClerkProvider publishableKey={clerkPubKey}>
    <CartProvider>
    <html lang="en">
      <body 
       className={inter.className}>
      <LoadingBar/>
      <Anouce/>
      <Header/>
        {children}
        <Footer/>

        </body>
    </html>
    </CartProvider>
    </ClerkProvider>
  );
}
