from datetime import datetime

from datetime import datetime, timedelta, timezone

from app.auth import hash_password
from app.database import SessionLocal
from app.models import Notification, Product, PromoCode, User


def seed_database():
    db = SessionLocal()
    try:
        # Check which categories already have products to avoid duplicates
        existing_categories = set()
        for cat in db.query(Product.category).distinct().all():
            if cat[0]:
                existing_categories.add(cat[0])

        # Create admin if not exists
        admin = db.query(User).filter(User.is_admin == True).first()
        if not admin:
            admin = db.query(User).filter(User.username == "admin").first()
            if admin:
                admin.is_admin = True
                db.flush()
                print("✅ Promoted existing 'admin' user to admin!")
            else:
                admin = User(
                    username="admin",
                    email="admin@shop.co",
                    hashed_password=hash_password("admin123"),
                    is_admin=True,
                    full_name="Admin",
                )
                db.add(admin)
                db.flush()

        products_data = [
            # ================================================================
            #  NEW ARRIVALS (8 products - latest season)
            # ================================================================
            Product(
                title="T-SHIRT WITH TAPE DETAILS",
                slug="t-shirt-with-tape-details",
                price=140,
                old_price=180,
                img_url="/products/product_1.png",
                img1="/products/product_2.png",
                img2="/products/product_3.png",
                description="A stylish t-shirt with unique tape detailing along the shoulders. Perfect for a casual day out with friends or a relaxed weekend vibe.",
                category="new_arrivals",
                rating=4.5,
                colors='["#4F4631","#314F4A","#31344F","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="SKINNY FIT JEANS",
                slug="skinny-fit-jeans",
                price=120,
                old_price=200,
                img_url="/products/product_4.png",
                img1="/products/product_5.png",
                img2="/products/product_6.png",
                description="Slim-fit jeans with a flattering cut and comfortable stretch. A great pair to complement your casual wardrobe for any occasion.",
                category="new_arrivals",
                rating=4.5,
                colors='["#314F4A","#000000","#4F4631"]',
                sizes='["28","30","32","34","36"]',
            ),
            Product(
                title="CHECKERED SHIRT",
                slug="checkered-shirt",
                price=120,
                old_price=160,
                img_url="/products/product_7.png",
                img1="/products/product_8.png",
                img2="/products/product_9.png",
                description="A trendy checkered shirt for a laid-back, yet stylish look. Made from soft fabric for all-day comfort and breathability.",
                category="new_arrivals",
                rating=4.5,
                colors='["#31344F","#4F4631","#314F4A"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="SLEEVE STRIPED T-SHIRT",
                slug="sleeve-striped-t-shirt",
                price=120,
                old_price=200,
                img_url="/products/product_10.png",
                img1="/products/product_11.png",
                img2="/products/product_12.png",
                description="This striped t-shirt adds a sporty touch with its bold sleeve design. A versatile piece for any casual occasion or workout.",
                category="new_arrivals",
                rating=4.5,
                colors='["#4F4631","#314F4A","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="CLASSIC DENIM JACKET",
                slug="classic-denim-jacket",
                price=280,
                old_price=350,
                img_url="/products/product_13.png",
                img1="/products/product_14.png",
                description="A timeless denim jacket that never goes out of style. Perfect for layering over any outfit for a rugged, classic look.",
                category="new_arrivals",
                rating=4.5,
                colors='["#314F4A","#4F4631"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="CASUAL LINEN SHIRT",
                slug="casual-linen-shirt",
                price=160,
                old_price=200,
                img_url="/products/product_15.png",
                img1="/products/product_16.png",
                img2="/products/product_17.png",
                description="Lightweight linen shirt perfect for summer days. Breathable fabric keeps you cool while maintaining a sharp, polished appearance.",
                category="new_arrivals",
                rating=4.5,
                colors='["#FFFFFF","#E5E5E5","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="COTTON CREW NECK SWEATER",
                slug="cotton-crew-neck-sweater",
                price=190,
                old_price=240,
                img_url="/products/product_18.png",
                img1="/products/product_19.png",
                description="A soft cotton crew neck sweater ideal for cooler days. Comfortable, warm, and easy to style with jeans or chinos.",
                category="new_arrivals",
                rating=4.5,
                colors='["#4F4631","#314F4A","#31344F","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="UTILITY CARGO PANTS",
                slug="utility-cargo-pants",
                price=150,
                old_price=190,
                img_url="/products/product_20.png",
                img1="/products/product_21.png",
                description="Durable cargo pants with multiple pockets for a functional yet fashionable look. Great for outdoor adventures or streetwear styling.",
                category="new_arrivals",
                rating=4.5,
                colors='["#4F4631","#000000","#314F4A"]',
                sizes='["28","30","32","34","36"]',
            ),

            # ================================================================
            #  T-SHIRTS COLLECTION (8 products)
            # ================================================================
            Product(
                title="COURAGE GRAPHIC T-SHIRT",
                slug="courage-graphic-t-shirt",
                price=145,
                img_url="/products/product_22.png",
                img1="/products/product_23.png",
                description="A bold graphic tee featuring an inspiring 'Courage' message. Perfect for making a statement while staying comfortable and trendy.",
                category="t-shirts",
                rating=4.5,
                colors='["#31344F","#4F4631","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="VINTAGE LOGO TEE",
                slug="vintage-logo-tee",
                price=95,
                old_price=130,
                img_url="/products/product_24.png",
                img1="/products/product_25.png",
                description="A vintage-style logo t-shirt that brings retro vibes to your everyday look. Soft cotton fabric for maximum comfort.",
                category="t-shirts",
                rating=4.5,
                colors='["#000000","#FFFFFF","#4F4631"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="BASIC CREW NECK TEE",
                slug="basic-crew-neck-tee",
                price=80,
                old_price=110,
                img_url="/products/product_26.png",
                img1="/products/product_27.png",
                description="The essential crew neck tee every wardrobe needs. Clean lines, premium cotton, and a perfect fit for any casual occasion.",
                category="t-shirts",
                rating=4.5,
                colors='["#000000","#FFFFFF","#4F4631","#314F4A"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="STRIPED POLO TEE",
                slug="striped-polo-tee",
                price=130,
                old_price=170,
                img_url="/products/product_28.png",
                img1="/products/product_29.png",
                description="A classic polo with stylish stripes. Combines the comfort of a t-shirt with the polished look of a polo collar.",
                category="t-shirts",
                rating=4.5,
                colors='["#4F4631","#31344F","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="ATHLETIC PERFORMANCE TEE",
                slug="athletic-performance-tee",
                price=110,
                img_url="/products/product_30.png",
                img1="/products/product_31.png",
                description="Moisture-wicking performance tee designed for workouts and active days. Lightweight fabric keeps you dry and comfortable.",
                category="t-shirts",
                rating=4.5,
                colors='["#000000","#314F4A","#4F4631"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="GRAPHIC PRINT TEE",
                slug="graphic-print-tee",
                price=100,
                old_price=140,
                img_url="/products/product_32.png",
                img1="/products/product_33.png",
                description="An eye-catching graphic print tee that adds personality to your outfit. Premium print that lasts wash after wash.",
                category="t-shirts",
                rating=4.5,
                colors='["#000000","#FFFFFF","#4F4631"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="HEAVYWEIGHT OVERSIZED TEE",
                slug="heavyweight-oversized-tee",
                price=125,
                img_url="/products/product_34.png",
                img1="/products/product_35.png",
                description="A heavyweight oversized t-shirt for that relaxed streetwear aesthetic. Thick, quality cotton with a roomy fit.",
                category="t-shirts",
                rating=4.5,
                colors='["#000000","#FFFFFF","#4F4631","#314F4A"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="TIE-DYE T-SHIRT",
                slug="tie-dye-t-shirt",
                price=115,
                old_price=150,
                img_url="/products/product_36.png",
                img1="/products/product_1.png",
                description="A vibrant tie-dye t-shirt that brings colorful energy to your wardrobe. Each piece has a unique pattern for a one-of-a-kind look.",
                category="t-shirts",
                rating=4.5,
                colors='["#4F4631","#314F4A","#31344F"]',
                sizes='["S","M","L","XL"]',
            ),

            # ================================================================
            #  SHIRTS COLLECTION (7 products)
            # ================================================================
            Product(
                title="VERTICAL STRIPED SHIRT",
                slug="vertical-striped-shirt",
                price=212,
                old_price=232,
                img_url="/products/product_2.png",
                img1="/products/product_3.png",
                img2="/products/product_4.png",
                description="A classic vertical striped shirt that pairs well with both jeans and dress pants. A stylish option for every season and occasion.",
                category="shirts",
                rating=4.5,
                colors='["#4F4631","#314F4A","#31344F"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="OXFORD BUTTON-DOWN SHIRT",
                slug="oxford-button-down-shirt",
                price=180,
                img_url="/products/product_5.png",
                img1="/products/product_6.png",
                description="A timeless Oxford button-down shirt crafted from premium cotton. The perfect blend of casual comfort and refined style.",
                category="shirts",
                rating=4.5,
                colors='["#FFFFFF","#4F4631","#000000","#E5E5E5"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="FLANNEL CHECK SHIRT",
                slug="flannel-check-shirt",
                price=160,
                old_price=200,
                img_url="/products/product_7.png",
                img1="/products/product_8.png",
                description="A warm flannel check shirt perfect for layering in cooler months. Soft brushed cotton with a classic plaid pattern.",
                category="shirts",
                rating=4.5,
                colors='["#4F4631","#31344F","#000000"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="DENIM WORK SHIRT",
                slug="denim-work-shirt",
                price=195,
                img_url="/products/product_9.png",
                img1="/products/product_10.png",
                description="A rugged denim work shirt built to last. Durable construction with a comfortable fit, ideal for casual or layered looks.",
                category="shirts",
                rating=4.5,
                colors='["#314F4A","#4F4631"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="LINEN RELAXED SHIRT",
                slug="linen-relaxed-shirt",
                price=175,
                old_price=220,
                img_url="/products/product_11.png",
                img1="/products/product_12.png",
                description="A relaxed-fit linen shirt for effortless summer style. Breathable, lightweight, and perfect for beach days or casual outings.",
                category="shirts",
                rating=4.5,
                colors='["#FFFFFF","#E5E5E5","#4F4631"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="PRINTED HAWAIIAN SHIRT",
                slug="printed-hawaiian-shirt",
                price=140,
                old_price=180,
                img_url="/products/product_13.png",
                img1="/products/product_14.png",
                description="A vibrant printed Hawaiian shirt that brings tropical vibes to your wardrobe. Fun, relaxed, and perfect for summer parties.",
                category="shirts",
                rating=4.5,
                colors='["#4F4631","#314F4A","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="FORMAL FIT DRESS SHIRT",
                slug="formal-fit-dress-shirt",
                price=220,
                old_price=280,
                img_url="/products/product_15.png",
                img1="/products/product_16.png",
                description="A sharp formal dress shirt for professional settings. Crisp finish, tailored fit, and premium fabric for a sophisticated look.",
                category="shirts",
                rating=4.5,
                colors='["#FFFFFF","#E5E5E5","#000000"]',
                sizes='["S","M","L","XL","XXL"]',
            ),

            # ================================================================
            #  PANTS / JEANS COLLECTION (7 products)
            # ================================================================
            Product(
                title="FADED SKINNY JEANS",
                slug="faded-skinny-jeans",
                price=210,
                old_price=260,
                img_url="/products/product_17.png",
                img1="/products/product_18.png",
                description="Skinny jeans with a trendy faded look, offering a sleek fit and ultimate comfort for daily wear and nights out.",
                category="pants",
                rating=4.5,
                colors='["#4F4631","#31344F","#000000"]',
                sizes='["28","30","32","34","36"]',
            ),
            Product(
                title="SLIM CHINO PANTS",
                slug="slim-chino-pants",
                price=160,
                old_price=200,
                img_url="/products/product_19.png",
                img1="/products/product_20.png",
                description="Classic slim chino pants that bridge the gap between casual and formal. Versatile enough for the office or a night out.",
                category="pants",
                rating=4.5,
                colors='["#4F4631","#000000","#314F4A","#E5E5E5"]',
                sizes='["28","30","32","34","36"]',
            ),
            Product(
                title="RELAXED FIT CARGO PANTS",
                slug="relaxed-fit-cargo-pants",
                price=175,
                img_url="/products/product_21.png",
                img1="/products/product_22.png",
                description="Relaxed cargo pants with ample pocket space for a utilitarian look. Comfortable fit perfect for streetwear and outdoor activities.",
                category="pants",
                rating=4.5,
                colors='["#4F4631","#000000","#314F4A"]',
                sizes='["28","30","32","34","36"]',
            ),
            Product(
                title="TAILORED WOOL TROUSERS",
                slug="tailored-wool-trousers",
                price=250,
                old_price=320,
                img_url="/products/product_23.png",
                img1="/products/product_24.png",
                description="Premium tailored wool trousers for a sophisticated look. Ideal for formal events, business meetings, or elevating your style.",
                category="pants",
                rating=4.5,
                colors='["#000000","#4F4631","#31344F"]',
                sizes='["28","30","32","34","36"]',
            ),
            Product(
                title="DISTRESSED STRAIGHT JEANS",
                slug="distressed-straight-jeans",
                price=190,
                old_price=240,
                img_url="/products/product_25.png",
                img1="/products/product_26.png",
                description="Straight-cut jeans with distressed detailing for an edgy, lived-in look. A wardrobe staple for casual, rugged style.",
                category="pants",
                rating=4.5,
                colors='["#4F4631","#000000"]',
                sizes='["28","30","32","34","36"]',
            ),
            Product(
                title="JOGGER SWEATPANTS",
                slug="jogger-sweatpants",
                price=130,
                img_url="/products/product_27.png",
                img1="/products/product_28.png",
                description="Comfortable jogger sweatpants with an elastic cuffed hem. Perfect for lounging, workouts, or casual streetwear looks.",
                category="pants",
                rating=4.5,
                colors='["#000000","#4F4631","#314F4A"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="WIDE LEG TROUSERS",
                slug="wide-leg-trousers",
                price=185,
                old_price=230,
                img_url="/products/product_29.png",
                img1="/products/product_30.png",
                description="On-trend wide leg trousers offering a modern silhouette. Flowing fabric creates an elegant, fashion-forward look.",
                category="pants",
                rating=4.5,
                colors='["#000000","#4F4631","#E5E5E5"]',
                sizes='["S","M","L","XL"]',
            ),

            # ================================================================
            #  SHORTS COLLECTION (5 products)
            # ================================================================
            Product(
                title="LOOSE FIT BERMUDA SHORTS",
                slug="loose-fit-bermuda-shorts",
                price=80,
                old_price=110,
                img_url="/products/product_31.png",
                img1="/products/product_32.png",
                description="Relaxed-fit bermuda shorts perfect for warm weather. A must-have for comfort during summer months and beach vacations.",
                category="shorts",
                rating=4.5,
                colors='["#314F4A","#4F4631","#000000","#E5E5E5"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="ATHLETIC TRAINING SHORTS",
                slug="athletic-training-shorts",
                price=95,
                img_url="/products/product_33.png",
                img1="/products/product_34.png",
                description="Lightweight athletic shorts designed for training and active lifestyles. Moisture-wicking fabric keeps you cool during workouts.",
                category="shorts",
                rating=4.5,
                colors='["#000000","#4F4631","#314F4A"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="CHINO SHORTS",
                slug="chino-shorts",
                price=110,
                old_price=140,
                img_url="/products/product_35.png",
                img1="/products/product_36.png",
                description="Smart chino shorts that dress up or down with ease. Perfect for summer outings, barbecues, and casual Friday looks.",
                category="shorts",
                rating=4.5,
                colors='["#4F4631","#000000","#E5E5E5","#314F4A"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="DENIM CUTOFF SHORTS",
                slug="denim-cutoff-shorts",
                price=100,
                old_price=130,
                img_url="/products/product_1.png",
                img1="/products/product_2.png",
                description="Classic denim cutoff shorts for a casual summer vibe. Durable denim with a relaxed, broken-in feel from day one.",
                category="shorts",
                rating=4.5,
                colors='["#314F4A","#4F4631"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="SWIM TRUNKS",
                slug="swim-trunks",
                price=85,
                img_url="/products/product_3.png",
                img1="/products/product_4.png",
                description="Quick-dry swim trunks with a comfortable mesh lining. Perfect for beach days, pool parties, and tropical getaways.",
                category="shorts",
                rating=4.5,
                colors='["#4F4631","#000000","#31344F","#314F4A"]',
                sizes='["S","M","L","XL"]',
            ),

            # ================================================================
            #  OUTERWEAR COLLECTION (6 products)
            # ================================================================
            Product(
                title="CLASSIC TRENCH COAT",
                slug="classic-trench-coat",
                price=350,
                old_price=450,
                img_url="/products/product_5.png",
                img1="/products/product_6.png",
                description="A sophisticated trench coat that elevates any outfit. Water-resistant fabric with a timeless silhouette for all seasons.",
                category="outerwear",
                rating=4.5,
                colors='["#4F4631","#000000","#E5E5E5"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="PUFFER JACKET",
                slug="puffer-jacket",
                price=290,
                img_url="/products/product_7.png",
                img1="/products/product_8.png",
                description="A warm puffer jacket with quilted construction for maximum insulation. Lightweight yet incredibly warm for cold weather.",
                category="outerwear",
                rating=4.5,
                colors='["#000000","#4F4631","#314F4A","#31344F"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="BOMBER JACKET",
                slug="bomber-jacket",
                price=240,
                old_price=300,
                img_url="/products/product_9.png",
                img1="/products/product_10.png",
                description="A classic bomber jacket with a modern twist. Ribbed cuffs and hem with a sleek silhouette for a cool, casual look.",
                category="outerwear",
                rating=4.5,
                colors='["#4F4631","#000000","#314F4A"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="LEATHER BIKER JACKET",
                slug="leather-biker-jacket",
                price=420,
                old_price=520,
                img_url="/products/product_11.png",
                img1="/products/product_12.png",
                description="A premium leather biker jacket that makes a bold statement. Asymmetric zip, lapel collar, and timeless rebel style.",
                category="outerwear",
                rating=4.5,
                colors='["#000000","#4F4631"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="SOFT SHELL PARKA",
                slug="soft-shell-parka",
                price=310,
                old_price=390,
                img_url="/products/product_13.png",
                img1="/products/product_14.png",
                description="A versatile soft shell parka built for unpredictable weather. Wind-resistant, water-repellent, and lined for extra warmth.",
                category="outerwear",
                rating=4.5,
                colors='["#4F4631","#000000","#314F4A"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="DENIM TRUCKER JACKET",
                slug="denim-trucker-jacket",
                price=220,
                old_price=280,
                img_url="/products/product_15.png",
                img1="/products/product_16.png",
                description="A classic denim trucker jacket with button front and chest pockets. A timeless layering piece for any casual wardrobe.",
                category="outerwear",
                rating=4.5,
                colors='["#314F4A","#4F4631"]',
                sizes='["S","M","L","XL"]',
            ),

            # ================================================================
            #  HOODIES & SWEATSHIRTS (5 products)
            # ================================================================
            Product(
                title="PULLOVER HOODIE",
                slug="pullover-hoodie",
                price=160,
                img_url="/products/product_17.png",
                img1="/products/product_18.png",
                description="A classic pullover hoodie with a kangaroo pocket and adjustable drawstring hood. Essential comfort for cooler days.",
                category="hoodies",
                rating=4.5,
                colors='["#000000","#4F4631","#314F4A","#FFFFFF"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="ZIP-UP FLEECE HOODIE",
                slug="zip-up-fleece-hoodie",
                price=180,
                old_price=230,
                img_url="/products/product_19.png",
                img1="/products/product_20.png",
                description="A cozy zip-up fleece hoodie perfect for layering. Soft brushed interior keeps you warm while the zip front offers easy wear.",
                category="hoodies",
                rating=4.5,
                colors='["#4F4631","#000000","#314F4A","#31344F"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="GRAPHIC PRINT HOODIE",
                slug="graphic-print-hoodie",
                price=190,
                img_url="/products/product_21.png",
                img1="/products/product_22.png",
                description="A bold graphic print hoodie that stands out from the crowd. Premium screen-printed design on heavyweight cotton fleece.",
                category="hoodies",
                rating=4.5,
                colors='["#000000","#4F4631","#FFFFFF"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="CREW NECK SWEATSHIRT",
                slug="crew-neck-sweatshirt",
                price=140,
                old_price=180,
                img_url="/products/product_23.png",
                img1="/products/product_24.png",
                description="A classic crew neck sweatshirt made from heavyweight cotton. Ribbed cuffs and hem with a comfortable, timeless fit.",
                category="hoodies",
                rating=4.5,
                colors='["#4F4631","#000000","#314F4A","#E5E5E5"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="OVERSIZED CROP HOODIE",
                slug="oversized-crop-hoodie",
                price=155,
                old_price=200,
                img_url="/products/product_25.png",
                img1="/products/product_26.png",
                description="An oversized cropped hoodie with a relaxed, fashion-forward silhouette. Perfect for pairing with high-waisted jeans or leggings.",
                category="hoodies",
                rating=4.5,
                colors='["#000000","#4F4631","#FFFFFF"]',
                sizes='["S","M","L","XL"]',
            ),

            # ================================================================
            #  DRESSES COLLECTION (5 products)
            # ================================================================
            Product(
                title="FLORAL MIDI DRESS",
                slug="floral-midi-dress",
                price=200,
                old_price=260,
                img_url="/products/product_27.png",
                img1="/products/product_28.png",
                description="A beautiful floral midi dress with a graceful flow. Perfect for spring outings, garden parties, or romantic date nights.",
                category="dresses",
                rating=4.5,
                colors='["#4F4631","#314F4A","#31344F"]',
                sizes='["XS","S","M","L","XL"]',
            ),
            Product(
                title="LITTLE BLACK DRESS",
                slug="little-black-dress",
                price=230,
                img_url="/products/product_29.png",
                img1="/products/product_30.png",
                description="The iconic little black dress that every wardrobe needs. Elegant, versatile, and perfect for any occasion from cocktails to dinner.",
                category="dresses",
                rating=4.5,
                colors='["#000000"]',
                sizes='["XS","S","M","L","XL"]',
            ),
            Product(
                title="SUMMER MAXI DRESS",
                slug="summer-maxi-dress",
                price=180,
                old_price=230,
                img_url="/products/product_31.png",
                img1="/products/product_32.png",
                description="A flowing summer maxi dress that brings effortless elegance to warm days. Lightweight fabric with a flattering silhouette.",
                category="dresses",
                rating=4.5,
                colors='["#FFFFFF","#E5E5E5","#4F4631","#314F4A"]',
                sizes='["XS","S","M","L","XL"]',
            ),
            Product(
                title="WRAP BODYCON DRESS",
                slug="wrap-bodycon-dress",
                price=190,
                old_price=250,
                img_url="/products/product_33.png",
                img1="/products/product_34.png",
                description="A flattering wrap bodycon dress that accentuates your curves. Stretch fabric with a wrap waist for a customized fit.",
                category="dresses",
                rating=4.5,
                colors='["#000000","#4F4631","#31344F"]',
                sizes='["XS","S","M","L","XL"]',
            ),
            Product(
                title="SHIFT DRESS WITH POCKETS",
                slug="shift-dress-with-pockets",
                price=170,
                img_url="/products/product_35.png",
                img1="/products/product_36.png",
                description="A comfortable shift dress with practical pockets. Clean lines and a relaxed fit make it perfect for work or weekend wear.",
                category="dresses",
                rating=4.5,
                colors='["#4F4631","#000000","#E5E5E5","#314F4A"]',
                sizes='["XS","S","M","L","XL"]',
            ),

            # ================================================================
            #  ACTIVEWEAR / SPORTS (5 products)
            # ================================================================
            Product(
                title="PERFORMANCE TRACK JACKET",
                slug="performance-track-jacket",
                price=200,
                old_price=260,
                img_url="/products/product_1.png",
                img1="/products/product_2.png",
                description="A lightweight performance track jacket with zippered pockets. Breathable fabric ideal for warm-ups, training, or casual wear.",
                category="activewear",
                rating=4.5,
                colors='["#000000","#4F4631","#314F4A"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="COMPRESSION LEGGINGS",
                slug="compression-leggings",
                price=140,
                img_url="/products/product_3.png",
                img1="/products/product_4.png",
                description="High-performance compression leggings with moisture-wicking technology. Supportive fit for intense workouts and active recovery.",
                category="activewear",
                rating=4.5,
                colors='["#000000","#4F4631","#31344F","#314F4A"]',
                sizes='["XS","S","M","L","XL"]',
            ),
            Product(
                title="RACERBACK TANK TOP",
                slug="racerback-tank-top",
                price=90,
                old_price=120,
                img_url="/products/product_5.png",
                img1="/products/product_6.png",
                description="A racerback tank top designed for freedom of movement during workouts. Lightweight, breathable fabric with a sleek fit.",
                category="activewear",
                rating=4.5,
                colors='["#000000","#FFFFFF","#4F4631","#314F4A"]',
                sizes='["XS","S","M","L","XL"]',
            ),
            Product(
                title="RUNNING SHORTS 2-IN-1",
                slug="running-shorts-2-in-1",
                price=110,
                img_url="/products/product_7.png",
                img1="/products/product_8.png",
                description="2-in-1 running shorts with built-in compression liner. Lightweight outer shell with secure zip pocket for essentials.",
                category="activewear",
                rating=4.5,
                colors='["#000000","#4F4631","#314F4A"]',
                sizes='["S","M","L","XL","XXL"]',
            ),
            Product(
                title="TRAINING HOODIE",
                slug="training-hoodie",
                price=175,
                old_price=220,
                img_url="/products/product_9.png",
                img1="/products/product_10.png",
                description="A training hoodie made from performance fabric. Breathable, stretchy, and designed to move with you during every workout.",
                category="activewear",
                rating=4.5,
                colors='["#000000","#4F4631","#314F4A"]',
                sizes='["S","M","L","XL","XXL"]',
            ),

            # ================================================================
            #  TOP SELLING (8 products - mix of bestsellers)
            # ================================================================
            Product(
                title="SIGNATURE BLAZER",
                slug="signature-blazer",
                price=320,
                old_price=420,
                img_url="/products/product_11.png",
                img1="/products/product_12.png",
                description="Our signature blazer with a tailored fit and premium construction. A versatile piece that transitions from boardroom to dinner seamlessly.",
                category="top_selling",
                rating=4.5,
                colors='["#000000","#4F4631","#31344F"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="CASHMERE BLEND SCARF",
                slug="cashmere-blend-scarf",
                price=120,
                old_price=160,
                img_url="/products/product_13.png",
                img1="/products/product_14.png",
                description="A luxuriously soft cashmere blend scarf that adds elegance to any outfit. A timeless accessory for cooler seasons.",
                category="top_selling",
                rating=4.5,
                colors='["#4F4631","#000000","#E5E5E5","#314F4A"]',
                sizes='["One Size"]',
            ),
            Product(
                title="LEATHER CROSSBODY BAG",
                slug="leather-crossbody-bag",
                price=280,
                old_price=350,
                img_url="/products/product_15.png",
                img1="/products/product_16.png",
                description="A premium leather crossbody bag with adjustable strap and multiple compartments. Functional fashion for everyday carry.",
                category="top_selling",
                rating=4.5,
                colors='["#000000","#4F4631"]',
                sizes='["One Size"]',
            ),
            Product(
                title="AVIATOR SUNGLASSES",
                slug="aviator-sunglasses",
                price=160,
                old_price=200,
                img_url="/products/product_17.png",
                img1="/products/product_18.png",
                description="Classic aviator sunglasses with UV protection and a lightweight metal frame. A timeless accessory for sunny days.",
                category="top_selling",
                rating=4.5,
                colors='["#000000","#4F4631"]',
                sizes='["One Size"]',
            ),
            Product(
                title="PREMIUM SNEAKERS",
                slug="premium-sneakers",
                price=240,
                old_price=300,
                img_url="/products/product_19.png",
                img1="/products/product_20.png",
                description="Premium leather sneakers with cushioned insoles for all-day comfort. A versatile footwear choice for casual and smart-casual looks.",
                category="top_selling",
                rating=4.5,
                colors='["#000000","#FFFFFF","#4F4631"]',
                sizes='["7","8","9","10","11","12"]',
            ),
            Product(
                title="LEATHER BELT",
                slug="leather-belt",
                price=95,
                img_url="/products/product_21.png",
                img1="/products/product_22.png",
                description="A genuine leather belt with a polished buckle. An essential accessory that completes any outfit with understated elegance.",
                category="top_selling",
                rating=4.5,
                colors='["#000000","#4F4631"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="WOVEN LEATHER WALLET",
                slug="woven-leather-wallet",
                price=130,
                old_price=170,
                img_url="/products/product_23.png",
                img1="/products/product_24.png",
                description="A handcrafted woven leather wallet with multiple card slots. Compact, stylish, and built to age beautifully over time.",
                category="top_selling",
                rating=4.5,
                colors='["#4F4631","#000000"]',
                sizes='["One Size"]',
            ),
            Product(
                title="CLASSIC WRISTWATCH",
                slug="classic-wristwatch",
                price=380,
                old_price=480,
                img_url="/products/product_25.png",
                img1="/products/product_26.png",
                description="A classic analog wristwatch with a stainless steel case and genuine leather strap. Timeless elegance for the modern individual.",
                category="top_selling",
                rating=4.5,
                colors='["#4F4631","#000000"]',
                sizes='["One Size"]',
            ),

            # ================================================================
            #  YOU MIGHT ALSO LIKE (6 products)
            # ================================================================
            Product(
                title="Polo with Contrast Trims",
                slug="polo-with-contrast-trims",
                price=212,
                old_price=242,
                img_url="/products/product_27.png",
                img1="/products/product_28.png",
                description="A stylish polo shirt with contrast trims, perfect for both casual and semi-formal occasions. Premium pique cotton fabric.",
                category="you_might_also_like",
                rating=4.5,
                colors='["#4F4631","#314F4A","#31344F","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="Gradient Graphic T-shirt",
                slug="gradient-graphic-t-shirt",
                price=145,
                img_url="/products/product_29.png",
                img1="/products/product_30.png",
                description="A modern graphic tee featuring a gradient design, adding a pop of color and creativity to your outfit. Soft cotton blend.",
                category="you_might_also_like",
                rating=4.5,
                colors='["#31344F","#4F4631","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="Polo with Tipping Details",
                slug="polo-with-tipping-details",
                price=180,
                old_price=220,
                img_url="/products/product_31.png",
                img1="/products/product_32.png",
                description="A polo shirt with tipping details along the collar and sleeves for a refined, sporty look. Classic meets contemporary.",
                category="you_might_also_like",
                rating=4.5,
                colors='["#4F4631","#000000","#FFFFFF"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="Black Striped T-shirt",
                slug="black-striped-t-shirt",
                price=120,
                old_price=150,
                img_url="/products/product_33.png",
                img1="/products/product_34.png",
                description="A sleek black striped t-shirt that adds a subtle edge to your casual look. Perfect for day-to-night wear with any bottom.",
                category="you_might_also_like",
                rating=4.5,
                colors='["#000000","#4F4631","#FFFFFF"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="SLIM FIT BLAZER",
                slug="slim-fit-blazer",
                price=350,
                old_price=440,
                img_url="/products/product_35.png",
                img1="/products/product_36.png",
                description="A sharp slim-fit blazer tailored for the modern wardrobe. Lightweight construction with a natural shoulder for versatile styling.",
                category="you_might_also_like",
                rating=4.5,
                colors='["#000000","#4F4631","#31344F"]',
                sizes='["S","M","L","XL"]',
            ),
            Product(
                title="CHUNKY KNIT CARDIGAN",
                slug="chunky-knit-cardigan",
                price=230,
                old_price=290,
                img_url="/products/product_1.png",
                img1="/products/product_2.png",
                description="A cozy chunky knit cardigan perfect for layering over any outfit. Oversized fit with a soft, textured wool blend.",
                category="you_might_also_like",
                rating=4.5,
                colors='["#4F4631","#E5E5E5","#000000"]',
                sizes='["S","M","L","XL"]',
            ),
        ]

        # Filter out products from categories that already exist
        products_to_add = [p for p in products_data if p.category not in existing_categories]
        new_categories_added = False
        if products_to_add:
            db.add_all(products_to_add)
            db.flush()
            added_cats = set(p.category for p in products_to_add)
            print(f"✅ Added {len(products_to_add)} new products in categories: {', '.join(added_cats)}")
            new_categories_added = True
        else:
            total = db.query(Product).count()
            print(f"✅ Products already seeded ({total} products across {len(existing_categories)} categories)")

        notifications = [
            Notification(
                user_id=admin.id,
                title="Welcome to SHOP.CO!",
                message="Welcome! Start exploring our latest collection and enjoy shopping.",
            ),
            Notification(
                user_id=admin.id,
                title="New Arrivals",
                message="Check out our newest collection - fresh styles just landed!",
            ),
            Notification(
                user_id=admin.id,
                title="Summer Sale",
                message="Enjoy up to 40% off on selected items. Limited time offer!",
            ),
        ]
        db.add_all(notifications)

        # Seed default promo codes
        existing_promo = db.query(PromoCode).filter(PromoCode.code == "DISCOUNT10").first()
        if not existing_promo:
            promo = PromoCode(
                code="DISCOUNT10",
                discount_amount=30,
                is_active=True,
                usage_limit=100,
            )
            db.add(promo)
            print("✅ Default promo code 'DISCOUNT10' created!")

        db.commit()
        total_products = db.query(Product).count()
        total_categories = db.query(Product.category).distinct().count()
        if new_categories_added:
            print(f"✅ Database updated! Now {total_products} products across {total_categories} categories!")
        else:
            print(f"✅ Database already up-to-date: {total_products} products across {total_categories} categories")
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
    finally:
        db.close()
